source_user:
  # 账号相关信息
  id: 1000012631
  username: mxq0001
  email: mxq0001@qq.com
  password: m1234567
  sprite:
    owned: 50    # 象牙螺
    unown: 1     # 编程猫
  # 作品相关信息
  work:
    ide:
      published_work_id: 21000002
      unpublish_work_id: 21000003
      deleted_temporarily_work_id: 21000004
      deleted_permanently_work_id: 21000005
      # 用于测试创建作品/修改作品/修改作品封面，bcm文件实际上就是经过处理的json字符串
      # work_url未加密，bcmc_url有加密(可选)，作品播放内容根据bcmc_url展示
      work_url: https://test.bcmcdn.com/kitten/ByW-83V1N.bcm
      preview_url: https://test.bcmcdn.com/kitten/SkbbU3E1N
      bcmc_url: https://test.bcmcdn.com/kitten/SkMW83VyV.bcmc
    boxv1:
      work_url: https://static.codemao.cn/a550635c-c592-49f6-a0ec-7febd50a2a60.bcm
      preview_url: https://preview.codemao.cn/FtjU5vGuYhkXIv37QUcQ-DMJbSch
    # 为了避免产生脏数据导致打开作品时报错，所以work_url必须是同类型url
    boxv2:
      published_work_id: 21000006   # 已发布
      work_url: https://static.codemao.cn/box/H1vYhAE-V.bcm
      preview_url: https://obxuuymk6.qnssl.com/default_preview.png
      bcmc_url: https://static.codemao.cn/box/HkDY2RVbE.bcmc
    wood:
      # 未发布
      work_id: 21000007
    nemo:
      work_id: 21000008
      work_url: https://test.bcmcdn.com/nemo/HJq-zvZpX.bcm
      preview_url: https://test.bcmcdn.com/nemo/Bk9-MD-pQ.cover


target_user:
  # 账号相关信息
  id: 1000012686
  username: mxq0002
  password: m1234567
  # 用户无代表精灵
  work:
    ide:
      published_work_id: 21000009           # 已发布可购买
      published_unfork_work_id: 21000010    # 已发布不可购买
      unpublish_work_id: 21000011           # 未发布
      deleted_temporarily_work_id: 21000013  # 临时删除
      deleted_permanently_work_id: 21000014  # 永久删除
    nemo:
      work_id: 21000015    # 未发布
  